/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CalendarView`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/OneThingMode`; params?: Router.UnknownInputParams; } | { pathname: `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Info`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TimeInput`; params?: Router.UnknownInputParams; } | { pathname: `/ResetPass`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/DotLoader`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EditTaskDialog`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/AppContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CalendarView`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/OneThingMode`; params?: Router.UnknownOutputParams; } | { pathname: `/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Info`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TimeInput`; params?: Router.UnknownOutputParams; } | { pathname: `/ResetPass`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/DotLoader`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/EditTaskDialog`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/AppContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/CalendarView${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/OneThingMode${`?${string}` | `#${string}` | ''}` | `/Settings${`?${string}` | `#${string}` | ''}` | `/../components/Info${`?${string}` | `#${string}` | ''}` | `/../components/TimeInput${`?${string}` | `#${string}` | ''}` | `/ResetPass${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/../components/Dashboard${`?${string}` | `#${string}` | ''}` | `/../components/DotLoader${`?${string}` | `#${string}` | ''}` | `/../components/EditTaskDialog${`?${string}` | `#${string}` | ''}` | `/../components/Settings${`?${string}` | `#${string}` | ''}` | `/../contexts/AppContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CalendarView`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/OneThingMode`; params?: Router.UnknownInputParams; } | { pathname: `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Info`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TimeInput`; params?: Router.UnknownInputParams; } | { pathname: `/ResetPass`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/DotLoader`; params?: Router.UnknownInputParams; } | { pathname: `/../components/EditTaskDialog`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/AppContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
